### The mathematical trick of self attention

In [82]:
import torch
from torch.nn import functional as F

In [6]:
torch.manual_seed(69)
# We have 8 tokens in a bactch and 4 batches !
batch, time, channel = 4,8,2

x = torch.randn(batch, time, channel)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We would like for each token to get the average tokens before per channel, so that we can predict.
# Bag Of Words is the term used when we are averaging words.


In [12]:
# Size([4, 8, 2])
x

tensor([[[-0.5300, -1.3035],
         [ 0.4438,  1.2221],
         [ 1.0395,  0.9608],
         [ 0.4214,  0.7452],
         [-1.8389, -1.2497],
         [-0.2485,  0.1428],
         [-1.0509,  0.3527],
         [-0.0916,  0.0341]],

        [[-0.8986,  0.1022],
         [-0.6627, -0.1350],
         [-0.3983, -1.7892],
         [ 1.2785,  1.3351],
         [-0.3066,  1.0382],
         [ 1.2762,  0.0419],
         [-1.2794, -1.8432],
         [ 0.8633, -1.7786]],

        [[-0.8080, -0.8735],
         [ 0.9367, -1.2319],
         [ 1.5287, -0.2759],
         [-0.8625, -0.1915],
         [-0.4807, -1.4154],
         [ 0.0934, -0.2420],
         [-1.0300, -0.2034],
         [-0.6882, -0.0178]],

        [[ 1.1983, -0.8180],
         [-0.7297,  0.8256],
         [ 0.8756,  0.2960],
         [ 0.6394,  1.2406],
         [-1.2100, -0.9481],
         [ 0.6444,  0.2188],
         [-1.2224, -0.9322],
         [-0.3832,  1.4027]]])

In [75]:
xbow = torch.zeros((batch, time, channel))
for b in range(batch):
    print('-------> Batch number :', b)
    for t in range(time):
        print('    Time :', t, ' x[b, :t+1] :')
        xprev = x[b, :t+1]
        print(xprev)
        xbow[b,t] = torch.mean(xprev, 0)
        print()

-------> Batch number : 0
    Time : 0  x[b, :t+1] :
tensor([[-0.5300, -1.3035]])

    Time : 1  x[b, :t+1] :
tensor([[-0.5300, -1.3035],
        [ 0.4438,  1.2221]])

    Time : 2  x[b, :t+1] :
tensor([[-0.5300, -1.3035],
        [ 0.4438,  1.2221],
        [ 1.0395,  0.9608]])

    Time : 3  x[b, :t+1] :
tensor([[-0.5300, -1.3035],
        [ 0.4438,  1.2221],
        [ 1.0395,  0.9608],
        [ 0.4214,  0.7452]])

    Time : 4  x[b, :t+1] :
tensor([[-0.5300, -1.3035],
        [ 0.4438,  1.2221],
        [ 1.0395,  0.9608],
        [ 0.4214,  0.7452],
        [-1.8389, -1.2497]])

    Time : 5  x[b, :t+1] :
tensor([[-0.5300, -1.3035],
        [ 0.4438,  1.2221],
        [ 1.0395,  0.9608],
        [ 0.4214,  0.7452],
        [-1.8389, -1.2497],
        [-0.2485,  0.1428]])

    Time : 6  x[b, :t+1] :
tensor([[-0.5300, -1.3035],
        [ 0.4438,  1.2221],
        [ 1.0395,  0.9608],
        [ 0.4214,  0.7452],
        [-1.8389, -1.2497],
        [-0.2485,  0.1428],
        [-1.0509,

In [19]:
x[0]

tensor([[-0.5300, -1.3035],
        [ 0.4438,  1.2221],
        [ 1.0395,  0.9608],
        [ 0.4214,  0.7452],
        [-1.8389, -1.2497],
        [-0.2485,  0.1428],
        [-1.0509,  0.3527],
        [-0.0916,  0.0341]])

In [21]:
x[b, :t+1]

tensor([[ 1.1983, -0.8180],
        [-0.7297,  0.8256],
        [ 0.8756,  0.2960],
        [ 0.6394,  1.2406],
        [-1.2100, -0.9481],
        [ 0.6444,  0.2188],
        [-1.2224, -0.9322],
        [-0.3832,  1.4027]])

In [23]:
xprev[0]

tensor([ 1.1983, -0.8180])

In [24]:
mean_prev

tensor([-0.0234,  0.1606])

In [20]:
xbow[0]

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [38]:
torch.manual_seed(69)
a = torch.ones((3,3))
b = torch.randint(0,10,(3,2)).float()
print(a)
print(b)
print(a @ b) # dot product, produit scalaire

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 5.],
        [9., 3.],
        [2., 5.]])
tensor([[11., 13.],
        [11., 13.],
        [11., 13.]])


In [40]:
#  You can create a cumulate sum using this trorch.tril trick !

In [52]:
torch.manual_seed(69)
a = torch.tril(torch.ones((3,3)))
b = torch.randint(0,10,(3,2)).float()
print(a)
print(b)
print(a @ b) # dot product, produit scalaire

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
tensor([[0., 5.],
        [9., 3.],
        [2., 5.]])
tensor([[ 0.,  5.],
        [ 9.,  8.],
        [11., 13.]])


In [55]:
print(a)
torch.sum(a,0)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])


tensor([3., 2., 1.])

In [58]:
print(a)
torch.sum(a,0, keepdim = True)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])


tensor([[3., 2., 1.]])

In [54]:
print(a)
torch.sum(a,1)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])


tensor([1., 2., 3.])

|-----|-----|-----|
| a11 | a12 | a13 | (Row 1)
|-----|-----|-----|
| a21 | a22 | a23 | (Row 2)

torch.sum(matrix, 0): Summing Across Rows

| a11 + a21 | a12 + a22 | a13 + a23 | (Sum of each column)


torch.sum(matrix, 1): Summing Across Columns

| a11 + a12 + a13 | (Sum of elements in Row 1)
| a21 + a22 + a23 | (Sum of elements in Row 2)


- Setting dim=0 sums across rows, while dim=1 sums across columns.
- The output tensor's shape is affected based on the specified dimension.

Summing over axis 0 collapses the matrix vertically, producing a sum of elements column-wise.
Summing over axis 1 collapses the matrix horizontally, resulting in a sum of elements row-wise.

In [59]:
import torch

a = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Sum across rows, keeping the 0th dimension (1x3)
sum_with_dim = torch.sum(a, 0, keepdim=True)
print(sum_with_dim)  # Output: tensor([[5, 7, 9]])

# Sum across rows, removing the 0th dimension (3)
sum_without_dim = torch.sum(a, 0, keepdim=False)
print(sum_without_dim)  # Output: tensor([5, 7, 9])


tensor([[5, 7, 9]])
tensor([5, 7, 9])


Using keepdim=True is particularly useful when you need to perform further operations that require the input dimensions to remain consistent, such as when you want to divide by the sum or apply some weighted operation while preserving the original tensor shape for broadcasting compatibility.

In [49]:
torch.manual_seed(69)
a = torch.tril(torch.ones((3,3)))
a = a / torch.sum(a, 1, keepdim = True)
b = torch.randint(0,10,(3,2)).float()
print(a)
print(b)
print(a @ b) # dot product, produit scalaire

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[0., 5.],
        [9., 3.],
        [2., 5.]])
tensor([[0.0000, 5.0000],
        [4.5000, 4.0000],
        [3.6667, 4.3333]])


### Example

In [60]:
torch.manual_seed(69)
# We have 8 tokens in a bactch and 4 batches !
batch, time, channel = 4,8,2

x = torch.randn(batch, time, channel)
x.shape

torch.Size([4, 8, 2])

In [62]:
x

tensor([[[-0.5300, -1.3035],
         [ 0.4438,  1.2221],
         [ 1.0395,  0.9608],
         [ 0.4214,  0.7452],
         [-1.8389, -1.2497],
         [-0.2485,  0.1428],
         [-1.0509,  0.3527],
         [-0.0916,  0.0341]],

        [[-0.8986,  0.1022],
         [-0.6627, -0.1350],
         [-0.3983, -1.7892],
         [ 1.2785,  1.3351],
         [-0.3066,  1.0382],
         [ 1.2762,  0.0419],
         [-1.2794, -1.8432],
         [ 0.8633, -1.7786]],

        [[-0.8080, -0.8735],
         [ 0.9367, -1.2319],
         [ 1.5287, -0.2759],
         [-0.8625, -0.1915],
         [-0.4807, -1.4154],
         [ 0.0934, -0.2420],
         [-1.0300, -0.2034],
         [-0.6882, -0.0178]],

        [[ 1.1983, -0.8180],
         [-0.7297,  0.8256],
         [ 0.8756,  0.2960],
         [ 0.6394,  1.2406],
         [-1.2100, -0.9481],
         [ 0.6444,  0.2188],
         [-1.2224, -0.9322],
         [-0.3832,  1.4027]]])

In [63]:
weights = torch.tril(torch.ones(time, time))
weights

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
sum_weights = torch.sum(weights,1, keepdim=True)
sum_weights

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])

In [67]:
average_weights = weights/sum_weights
average_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [77]:
x.shape

torch.Size([4, 8, 2])

In [72]:
average_weights.shape

torch.Size([8, 8])

In [78]:
"""
x.shape is torch.Size([4, 8, 2])

average_weight.shape is torch.Size([8, 8])

What will happen is I do a dot multiply in Pytorch ? explain the logic


For matrix multiplication, the inner dimensions must match. In simpler terms, if you're multiplying matrices A and B where A is of shape (m, n) and B is of shape (n, p), the result will be of shape (m, p).


( time, time ) @ (batch, time, channel) ==> in Pytorch  : (batch, time, time) @ (batch, time, channel) => (batch, time, channel)
"""
(average_weights @ x).shape
#torch.Size([4, 8, 2])
"""
Given the result you've provided, it appears there's been a misunderstanding on my part regarding the handling of the operation given 
the tensor shapes in PyTorch. Let's clarify the correct behavior and logic behind it:

- `x.shape`: `[4, 8, 2]`
- `average_weights.shape`: `[8, 8]`

And the operation `average_weights @ x` gives a result of shape `[4, 8, 2]`.

Here's the corrected explanation based on the operation and its result:

1. **Tensor Broadcasting**: PyTorch allows broadcasting of the `average_weights` tensor across the batch dimension of `x` implicitly 
      during the matrix multiplication operation. This means `average_weights` is applied to each of the 4 matrices in `x` as 
      if it were a batch operation, even though `average_weights` doesn't explicitly have a batch dimension.

2. **Matrix Multiplication Logic**:
   - The operation treats `x` as a batch of 4 matrices of size `[8, 2]`.
   - `average_weights`, being an `[8, 8]` matrix, is compatible for multiplication with each `[8, 2]` matrix in `x`.
   - For each of the 4 matrices in `x`, the `average_weights` matrix is multiplied, resulting in 4 matrices of shape `[8, 2]`.

3. **Result Shape**: The operation effectively performs the matrix multiplication for each matrix in the batch separately, 
        maintaining the batch size (4) and the resultant matrix shape `[8, 2]` for each multiplication. 
        Hence, the overall result shape is `[4, 8, 2]`, which matches the shape you've observed.

This corrected explanation accounts for the behavior of PyTorch's matrix multiplication with broadcasting, 
where `average_weights` is applied to each item in the batch of `x`, yielding the result with the same batch dimension and 
the expected shape after the multiplication.
"""

torch.Size([4, 8, 2])

In [ ]:
   [8, 8] @ [4, 8, 2]

[4, 8, 8] @ [4, 8, 2]



In [73]:
x

tensor([[[-0.5300, -1.3035],
         [ 0.4438,  1.2221],
         [ 1.0395,  0.9608],
         [ 0.4214,  0.7452],
         [-1.8389, -1.2497],
         [-0.2485,  0.1428],
         [-1.0509,  0.3527],
         [-0.0916,  0.0341]],

        [[-0.8986,  0.1022],
         [-0.6627, -0.1350],
         [-0.3983, -1.7892],
         [ 1.2785,  1.3351],
         [-0.3066,  1.0382],
         [ 1.2762,  0.0419],
         [-1.2794, -1.8432],
         [ 0.8633, -1.7786]],

        [[-0.8080, -0.8735],
         [ 0.9367, -1.2319],
         [ 1.5287, -0.2759],
         [-0.8625, -0.1915],
         [-0.4807, -1.4154],
         [ 0.0934, -0.2420],
         [-1.0300, -0.2034],
         [-0.6882, -0.0178]],

        [[ 1.1983, -0.8180],
         [-0.7297,  0.8256],
         [ 0.8756,  0.2960],
         [ 0.6394,  1.2406],
         [-1.2100, -0.9481],
         [ 0.6444,  0.2188],
         [-1.2224, -0.9322],
         [-0.3832,  1.4027]]])

In [68]:
average_weights @ x

tensor([[[-0.5300, -1.3035],
         [-0.0431, -0.0407],
         [ 0.3178,  0.2932],
         [ 0.3437,  0.4062],
         [-0.0928,  0.0750],
         [-0.1188,  0.0863],
         [-0.2519,  0.1244],
         [-0.2319,  0.1131]],

        [[-0.8986,  0.1022],
         [-0.7807, -0.0164],
         [-0.6532, -0.6073],
         [-0.1703, -0.1217],
         [-0.1976,  0.1103],
         [ 0.0481,  0.0989],
         [-0.1416, -0.1786],
         [-0.0160, -0.3786]],

        [[-0.8080, -0.8735],
         [ 0.0643, -1.0527],
         [ 0.5525, -0.7937],
         [ 0.1987, -0.6432],
         [ 0.0628, -0.7976],
         [ 0.0679, -0.7050],
         [-0.0889, -0.6334],
         [-0.1638, -0.5564]],

        [[ 1.1983, -0.8180],
         [ 0.2343,  0.0038],
         [ 0.4481,  0.1012],
         [ 0.4959,  0.3860],
         [ 0.1547,  0.1192],
         [ 0.2363,  0.1358],
         [ 0.0279, -0.0168],
         [-0.0234,  0.1606]]])

In [76]:
xbow

tensor([[[-0.5300, -1.3035],
         [-0.0431, -0.0407],
         [ 0.3178,  0.2932],
         [ 0.3437,  0.4062],
         [-0.0928,  0.0750],
         [-0.1188,  0.0863],
         [-0.2519,  0.1244],
         [-0.2319,  0.1131]],

        [[-0.8986,  0.1022],
         [-0.7807, -0.0164],
         [-0.6532, -0.6073],
         [-0.1703, -0.1217],
         [-0.1976,  0.1103],
         [ 0.0481,  0.0989],
         [-0.1416, -0.1786],
         [-0.0160, -0.3786]],

        [[-0.8080, -0.8735],
         [ 0.0643, -1.0527],
         [ 0.5525, -0.7937],
         [ 0.1987, -0.6432],
         [ 0.0628, -0.7976],
         [ 0.0679, -0.7050],
         [-0.0889, -0.6334],
         [-0.1638, -0.5564]],

        [[ 1.1983, -0.8180],
         [ 0.2343,  0.0038],
         [ 0.4481,  0.1012],
         [ 0.4959,  0.3860],
         [ 0.1547,  0.1192],
         [ 0.2363,  0.1358],
         [ 0.0279, -0.0168],
         [-0.0234,  0.1606]]])

In [88]:
time

8

In [90]:
tril == 0,

(tensor([[False,  True,  True,  True,  True,  True,  True,  True],
         [False, False,  True,  True,  True,  True,  True,  True],
         [False, False, False,  True,  True,  True,  True,  True],
         [False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False,  True],
         [False, False, False, False, False, False, False, False]]),)

In [87]:
tril[:time, :time] == 0,

(tensor([[False,  True,  True,  True,  True,  True,  True,  True],
         [False, False,  True,  True,  True,  True,  True,  True],
         [False, False, False,  True,  True,  True,  True,  True],
         [False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False,  True],
         [False, False, False, False, False, False, False, False]]),)

In [85]:
tril = torch.tril(torch.ones(time, time))
weights = torch.zeros(time, time)
# Don't look at the future so set it to -inf
weights = weights.masked_fill(tril[:time, :time] == 0, float('-inf')) # (Batch, Time, Time) 
# softmax exp(-inf) = 0, exp(0) = 1 and then softmax on dim=1 (across row) with sum up the Zeros
weights = F.softmax(weights, dim=-1) # (B, T, T)
xbow3 = weights @ x

In [86]:
torch.allclose(xbow, xbow3)

True

In [1]:
import torch
from collections import Counter
import random
import re
from torch.utils.data import Dataset, DataLoader
import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split



file_path = '/Users/jaafarbendriss/First-LLM/dataset/black_hole_wiki.txt'

# Open the file and read its content
with open(file_path, 'r') as file:
    file_content = file.read()

raw_text = file_content

def add_start_end_sentence(text):
    return "start-of-sentence " + text.replace("."," end-of-sentence start-of-sentence")


def remove_citations(text):
    pattern = r"\[\d+\]"
    cleaned_text = re.sub(pattern, "", text)    
    return cleaned_text

def remove_spaces(text):
    pattern = r"\s+"
    cleaned_text = re.sub(pattern, " ", text)    
    return cleaned_text

def preprocess(text: str):
    return remove_spaces(remove_citations(add_start_end_sentence(text).lower().replace("(","").replace(")","").replace(" s ","").replace("\\","").replace("'"," ").replace('"',' ').replace(","," ").replace("\ s"," ").replace("\n"," ")))

preprocessed_text = preprocess(raw_text)

Counter(preprocessed_text.split(" ")).most_common(20)

preprocessed_text_array = preprocessed_text.split(" ")


print(preprocessed_text_array[0:100])

from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

tokenizer = get_tokenizer("basic_english")

tokens = tokenizer(preprocessed_text)

preprocessed_text = preprocessed_text.replace("end-of-sentence start-of-sentence", "end-of-sentence69696969start-of-sentence")
splited_data = preprocessed_text.split("69696969")

train_data =  [(i,sentence) for i, sentence in zip( range(0,len(splited_data)), splited_data  )]
train_iter = iter(train_data)


['start-of-sentence', 'object', 'that', 'has', 'a', 'no-return', 'boundary', 'for', 'other', 'uses', 'see', 'black', 'hole', 'disambiguation', 'end-of-sentence', 'start-of-sentence', 'direct', 'radio', 'image', 'of', 'a', 'supermassive', 'black', 'hole', 'at', 'the', 'core', 'of', 'messier', '87', 'animated', 'simulation', 'of', 'a', 'schwarzschild', 'black', 'hole', 'with', 'a', 'galaxy', 'passing', 'behind', 'end-of-sentence', 'start-of-sentence', 'around', 'the', 'time', 'of', 'alignment', 'extreme', 'gravitational', 'lensing', 'of', 'the', 'galaxy', 'is', 'observed', 'end-of-sentence', 'start-of-sentence', 'a', 'black', 'hole', 'is', 'a', 'region', 'of', 'spacetime', 'where', 'gravity', 'is', 'so', 'strong', 'that', 'nothing', 'including', 'light', 'and', 'other', 'electromagnetic', 'waves', 'has', 'enough', 'energy', 'to', 'escape', 'it', 'end-of-sentence', 'start-of-sentence', 'einstein', 's', 'theory', 'of', 'general', 'relativity', 'predicts', 'that', 'a', 'sufficiently', 'comp

In [2]:
raw_text[0]

"'"

In [24]:
next(train_iter)

(0,
 'start-of-sentence preface a chancery judge once had the kindness to inform me as one of a company of some hundred and fifty men and women not labouring under any suspicions of lunacy that the court of chancery though the shining subject of much popular prejudice at which point i thought the judge’s eye had a cast in my direction was almost immaculate end-of-sentence')

## Preparing training dataset using sliding window

In [25]:
class Vocab:

    #_list_of_sentences = None
    
    def __init__(self, list_of_sentences):
        self._list_of_sentences = list_of_sentences
        self.tokens = dict()

    def compute_tokens(self):
        all_words = set([w for stc in self._list_of_sentences for w in stc ])

        index = 0
        
        for sentence in self._list_of_sentences:
            for word in sentence.split(" "):
                if word not in self.tokens:
                    self.tokens[word] = index
                    index += 1
            

In [26]:
len(splited_data)

3731

In [27]:
myVocab = Vocab(splited_data)

len(myVocab._list_of_sentences)

3731

In [28]:
myVocab.compute_tokens()

In [29]:

myVocab.tokens

{'start-of-sentence': 0,
 'preface': 1,
 'a': 2,
 'chancery': 3,
 'judge': 4,
 'once': 5,
 'had': 6,
 'the': 7,
 'kindness': 8,
 'to': 9,
 'inform': 10,
 'me': 11,
 'as': 12,
 'one': 13,
 'of': 14,
 'company': 15,
 'some': 16,
 'hundred': 17,
 'and': 18,
 'fifty': 19,
 'men': 20,
 'women': 21,
 'not': 22,
 'labouring': 23,
 'under': 24,
 'any': 25,
 'suspicions': 26,
 'lunacy': 27,
 'that': 28,
 'court': 29,
 'though': 30,
 'shining': 31,
 'subject': 32,
 'much': 33,
 'popular': 34,
 'prejudice': 35,
 'at': 36,
 'which': 37,
 'point': 38,
 'i': 39,
 'thought': 40,
 'judge’s': 41,
 'eye': 42,
 'cast': 43,
 'in': 44,
 'my': 45,
 'direction': 46,
 'was': 47,
 'almost': 48,
 'immaculate': 49,
 'end-of-sentence': 50,
 'there': 51,
 'been': 52,
 'he': 53,
 'admitted': 54,
 'trivial': 55,
 'blemish': 56,
 'or': 57,
 'so': 58,
 'its': 59,
 'rate': 60,
 'progress': 61,
 'but': 62,
 'this': 63,
 'exaggerated': 64,
 'entirely': 65,
 'owing': 66,
 '“parsimony': 67,
 'public': 68,
 '”': 69,
 'guilt

In [30]:
def yield_tokens(data_iter):
    for _, text in data_iter:
        yield tokenizer(text)

#vocab = build_vocab_from_iterator(yield_tokens(train_iter), specials=["<unk>"])
#vocab.set_default_index(vocab["<unk>"])
#vocab(tokens[0:10])

In [31]:
token_map = myVocab.tokens #vocab.get_stoi()

In [32]:
splited_data[200]

'start-of-sentence is a new dress a new custom a new singer a new dancer a new form of jewellery a new dwarf or giant a new chapel a new anything to be set up? there are deferential people in a dozen callings whom my lady dedlock suspects of nothing but prostration before her who can tell you how to manage her as if she were a baby who do nothing but nurse her all their lives who humbly affecting to follow with profound subservience lead her and her whole troop after them; who in hooking one hook all and bear them off as lemuel gulliver bore away the stately fleet of the majestic lilliput end-of-sentence'

In [33]:
training_data = []

for sentence in splited_data:
    data=sentence.split()
    for i in range(1,len(data)):
        X=data[0:i]
        y = data[i]
        training_data.append((X,y))

In [34]:
len(training_data)

76182

In [35]:
training_data[20:21]

[(['start-of-sentence',
   'preface',
   'a',
   'chancery',
   'judge',
   'once',
   'had',
   'the',
   'kindness',
   'to',
   'inform',
   'me',
   'as',
   'one',
   'of',
   'a',
   'company',
   'of',
   'some',
   'hundred',
   'and'],
  'fifty')]

In [36]:
WINDOW = 10

In [37]:
# second method

training_data_cut = []

for sentence in splited_data:
    data=sentence.split()
    for i in range(1,len(data)):
        X=data[max([0,i-WINDOW]):i]
        y = data[i]
        training_data_cut.append((X,y))

In [38]:
training_data_cut[20:21]

[(['me', 'as', 'one', 'of', 'a', 'company', 'of', 'some', 'hundred', 'and'],
  'fifty')]

In [39]:
word_to_token = token_map

def word_to_token_wrapper(word: str) -> int:
    if word not in word_to_token:
        return word_to_token["<unk>"]
    return word_to_token[word]

def list_sentence_to_token(sentence_list)->int:
    return [word_to_token_wrapper(word) for word in sentence_list]

def sentence_to_token(sentence):
    return [word_to_token_wrapper(word) for word in sentence.split()]


In [40]:
sentence_to_token("black")

[440]

In [41]:
training_data_cut[4]

(['start-of-sentence', 'preface', 'a', 'chancery', 'judge'], 'once')

In [42]:
training_data_tokenized = [ (list_sentence_to_token(a),word_to_token_wrapper(b) ) for a,b in training_data_cut]

In [43]:
training_data_tokenized[110:115]

[([73, 74, 75, 44, 7, 76, 77, 78, 79, 80], 81),
 ([74, 75, 44, 7, 76, 77, 78, 79, 80, 81], 82),
 ([75, 44, 7, 76, 77, 78, 79, 80, 81, 82], 83),
 ([44, 7, 76, 77, 78, 79, 80, 81, 82, 83], 7),
 ([7, 76, 77, 78, 79, 80, 81, 82, 83, 7], 84)]

## training 

In [44]:
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim

class SentenceCompletionDataset(Dataset):
    def __init__(self, data, word_to_index):
        self.data = data
        self.word_to_index = word_to_index
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        input_sequence, target_word = self.data[idx]
        input_indices = [self.word_to_index[word] for word in input_sequence]
        target_index = self.word_to_index[target_word]
        return torch.tensor(input_indices, dtype=torch.long), torch.tensor(target_index, dtype=torch.long)



In [58]:

# Assuming train_data is a list of sentences
train_sentences, val_sentences = train_test_split(training_data_tokenized, test_size=0.5, random_state=42)

# Now, apply the masking and preparation logic to both train_sentences and val_sentences

In [59]:

class TokenDataset(Dataset):
    def __init__(self, data):
        self.data = data
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        tokens, target = self.data[idx]
        return torch.tensor(tokens, dtype=torch.long), torch.tensor(target, dtype=torch.long)

# Assuming `data` is your list of mappings
dataset = TokenDataset(data)
dataloader = DataLoader(dataset, batch_size=60, shuffle=True)

In [60]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):
    tokens, targets = zip(*batch)
    # Pad the sequences to the maximum length in the batch
    tokens_padded = pad_sequence([torch.tensor(seq) for seq in tokens], batch_first=True, padding_value=0)
    targets = torch.tensor(targets, dtype=torch.long)
    return tokens_padded, targets


In [61]:
len(train_sentences)

38091

In [62]:
vocab_size = len(word_to_token)
vocab_size

9233

In [63]:
import torch
import torch.nn as nn
import torch.optim as optim

class SimpleLM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim,dropout_rate=0.5):
        super(SimpleLM, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear1 = nn.Linear(embedding_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(dropout_rate)  # Add dropout layer

        self.linear2 = nn.Linear(hidden_dim, output_dim)
        
    def forward(self, tokens):
        embedded = self.embedding(tokens)  # [batch_size, seq_len, embedding_dim]
        # Aggregate embeddings, e.g., by averaging
        aggregated = embedded.mean(dim=1)  # [batch_size, embedding_dim]
        hidden = self.relu(self.linear1(aggregated))  # [batch_size, hidden_dim]
        output = self.linear2(hidden)  # [batch_size, output_dim]
        return output

# Hyperparameters
"""
embedding_dim = 60
hidden_dim = 30
"""
embedding_dim = 60
hidden_dim = 30
output_dim = vocab_size  # Same as vocab size for prediction

model = SimpleLM(vocab_size, embedding_dim, hidden_dim, output_dim)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [64]:
len(train_sentences)

38091

In [65]:
data = train_sentences

In [66]:
dataset = TokenDataset(data)
dataloader = DataLoader(dataset, batch_size=5, shuffle=False, collate_fn=collate_fn)


In [67]:
num_epochs = 100  # Or whatever suits your dataset

for epoch in range(num_epochs):
    total_loss = 0
    for tokens, target in dataloader:
        optimizer.zero_grad()
        output = model(tokens)
        loss = criterion(output, target.view(-1))
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
    if epoch %10 == 0:
        print(f'Epoch {epoch+1}, Loss: {total_loss/len(dataloader)}')

# batch 5 => Epoch 141, Loss: 0.3472299749050117
# batch 7 => Epoch 141, Loss: 0.3254897424296818

# batch 5 and window 5 => Epoch 141, Loss: 0.2996615952255913
"""
embedding_dim = 80
hidden_dim = 50
0.26723970297246136
"""

"""
embedding_dim = 40
hidden_dim = 20
0.37902324068592874
"""


"""
embedding_dim = 50
hidden_dim = 20
dropout = 0.5
0.3662537602579914
"""

"""
embedding_dim = 50
hidden_dim = 20
dropout = 0.5
New token technique : Loss: 0.33178764806329597

"""

/var/folders/l4/bv3z08h91lggkmhcp2n7yzh80000gn/T/ipykernel_77890/763346120.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tokens_padded = pad_sequence([torch.tensor(seq) for seq in tokens], batch_first=True, padding_value=0)


Epoch 1, Loss: 6.953255592235541
Epoch 11, Loss: 4.861751239652442
Epoch 21, Loss: 4.175530559920563
Epoch 31, Loss: 3.8444812300324456
Epoch 41, Loss: 3.644073111845261
Epoch 51, Loss: 3.5131063884614817
Epoch 61, Loss: 3.4258032961926883
Epoch 71, Loss: 3.3583802961567004
Epoch 81, Loss: 3.308972013420689
Epoch 91, Loss: 3.2768861328871766


'\nembedding_dim = 50\nhidden_dim = 20\ndropout = 0.5\nNew token technique : Loss: 0.33178764806329597\n\n'

In [69]:
train_sentences[10:15]

[([0, 2236, 12, 45, 2034, 14, 45], 2237),
 ([0, 205, 39, 199, 516, 14, 3124, 39, 607], 18),
 ([7, 4625, 14, 7, 593, 2343, 9, 4626, 119, 4627], 4628),
 ([250, 63, 191, 22, 228, 310, 1207, 3116, 36, 25], 8406),
 ([58, 1829, 12, 51, 127, 5942, 57, 238, 44, 7], 1456)]

In [70]:
seq = sentence_to_token("the black")
seq

[7, 440]

In [71]:
token_to_word = {token: word for word, token in word_to_token.items()}

def token_to_sentence(tokens):
    return " ".join([token_to_word[t] for t in tokens])

In [72]:
token_to_sentence([2, 1, 110, 160, 36])

'a preface with essential at'

In [73]:
sequence = [2, 1, 110, 160, 36]
sequence_tensor = torch.tensor(sequence).unsqueeze(0) 
sequence_tensor

tensor([[  2,   1, 110, 160,  36]])

In [74]:
model.eval()  # Set the model to evaluation mode
with torch.no_grad():  # Disable gradient computation
    output = model(sequence_tensor)
    predicted_token_id = output.argmax(dim=1).item()  # Get the index of the max log-probability
predicted_token_id

57

In [75]:
token_to_word[predicted_token_id]

'or'

In [92]:
TOPK = 3

def predict_missing_word(sentence="black hole is the biggest object in the"):
    last_K = " ".join(sentence.split()[-WINDOW:])
    #print(last_K)                  
    sequence = sentence_to_token(last_K)
    sequence_tensor = torch.tensor(sequence).unsqueeze(0)  # Add batch dimension
    model.eval()  # Set the model to evaluation mode
    with torch.no_grad():  # Disable gradient computation
        output = model(sequence_tensor)
        predicted_token_id = output.argmax(dim=1).item()  # Get the index of the max log-probability
        _, top5_indices = torch.topk(output[0], TOPK)
        predicted_token_id = random.choice(top5_indices.tolist())

    # Assuming you have a token_to_word dictionary
    token_to_word = {token: word for word, token in word_to_token.items()}
    predicted_word = token_to_word[predicted_token_id]
    return predicted_word

In [93]:
def predict_missing_token(tokens):
               
    sequence = tokens[-WINDOW:]
    sequence_tensor = torch.tensor(sequence).unsqueeze(0)  # Add batch dimension
    model.eval()  # Set the model to evaluation mode
    with torch.no_grad():  # Disable gradient computation
        output = model(sequence_tensor)
        predicted_token_id = output.argmax(dim=1).item()  # Get the index of the max log-probability
        
        #_, top5_indices = torch.topk(output[0], TOPK)
        #predicted_token_id = random.choice(top5_indices.tolist())

    return predicted_token_id

In [94]:
def generate_sentence(start_word = "start-of-sentence"):
    next_word = start_word
    #next_word = "einstein"
    words = []
    sentence = next_word
    words.append(next_word)
    limit = 0
    while next_word != "end-of-sentence" and limit<20:
        #print("input ",sentence)
        next_word = predict_missing_word(sentence)
        #print("output ",next_word)
        words.append(next_word)
        sentence = " ".join(words)
        limit += 1
    
    return " ".join(words)

In [95]:
for _ in range(10):
    print(generate_sentence())

start-of-sentence is no to child worse to to but never sit to anything tell it know else no much end-of-sentence
start-of-sentence the small of guardians you suppose seen themselves cousin beg again the said ada mr classicality classicality classicality classicality end-of-sentence
start-of-sentence the floor and back away either pale and the clear the things face head end-of-sentence
start-of-sentence is no us in station the court long grey great casts myself end-of-sentence
start-of-sentence a decaying her opportunity and and hold and did towards order a knew knew appearance to of the of of
start-of-sentence the floor of and peeps parisians law convivial admiration expense quiet to can’t to and stuff had he to me
start-of-sentence is no end-of-sentence
start-of-sentence a consummate but low country else all about about about no us to to end-of-sentence
start-of-sentence is no us end-of-sentence
start-of-sentence a consummate of low its hand head inspiring slangular teeth lemon-juice 

In [90]:
correct = 0

for s in val_sentences:
    #print(s)
    predicted_token = predict_missing_token(s[0]) 
    #print("predicted token = ", predicted_token)
    answer = predicted_token == s[1]

    if answer:
        correct += answer

print()
print(correct,len(val_sentences))
"""
embedding_dim = 80
hidden_dim = 50
259 3462
"""
# 



1287 38091


'\nembedding_dim = 80\nhidden_dim = 50\n259 3462\n'

In [91]:
correct = 0

for s in train_sentences:
    #print(s)
    predicted_token = predict_missing_token(s[0]) 
    #print("predicted token = ", predicted_token)
    answer = predicted_token == s[1]

    if answer:
        correct += answer

print()
print(correct,len(train_sentences))
"""
embedding_dim = 80
hidden_dim = 50
7261 8076
"""



7143 38091


'\nembedding_dim = 80\nhidden_dim = 50\n7261 8076\n'