## Basic Pytorch

In [1]:
import torch

In [2]:
data = [[1,2,3],[4,5,6]]

In [3]:
x_data = torch.tensor(data)

x_data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
x_rand = torch.rand_like(x_data, dtype=float)
x_rand

tensor([[0.7314, 0.4835, 0.2963],
        [0.2437, 0.6342, 0.0052]], dtype=torch.float64)

In [5]:
x1 = torch.tensor([[4],[5]]) # 2,1
x2 = torch.tensor([[7]]) # 1,1
torch.matmul(x1,x2) # 2,1

tensor([[28],
        [35]])

In [6]:
x1 @ x2

tensor([[28],
        [35]])

## Simple ANN

In [7]:
import os
from torch import nn
from torch.utils.data import dataloader
from torchvision import datasets, transforms

In [8]:
class SimpleANN(nn.Module):

    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(5, 512),  # Increased neurons
            nn.ReLU(),
            nn.Linear(512, 256),  # Added more layers
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 1),  # Assuming a single output for simplicity
        )
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


model = SimpleANN()        


In [9]:
model = SimpleANN()

In [163]:
# Example x_data with batch size N=3, and each sample having 5 features
x_data = torch.randn(3, 5)  # Generates a tensor of shape [3, 5] with random values

In [10]:
torch.manual_seed(69)
tensor_rand = torch.randn(5,3)
# torch.randn(rows, cols)


torch.sum(tensor_rand, dim=1, keepdim = True) # sum on the row level, horizontally
tensor_rand

tensor([[-0.5259, -2.6043, -0.6448],
        [ 1.4356, -0.5796, -0.7254],
        [ 1.6112, -0.0703,  0.4757],
        [-0.3330, -0.0810, -1.2897],
        [-1.1969,  0.6707, -1.2555]])

In [15]:
masked_tensor = tensor_rand.masked_fill(tensor_rand>0,float("-inf"))
masked_tensor

tensor([[-0.5259, -2.6043, -0.6448],
        [   -inf, -0.5796, -0.7254],
        [   -inf, -0.0703,    -inf],
        [-0.3330, -0.0810, -1.2897],
        [-1.1969,    -inf, -1.2555]])

In [16]:
torch.softmax(masked_tensor, dim=-1)

tensor([[0.4968, 0.0622, 0.4411],
        [0.0000, 0.5364, 0.4636],
        [0.0000, 1.0000, 0.0000],
        [0.3744, 0.4817, 0.1438],
        [0.5146, 0.0000, 0.4854]])

In [164]:
x_data

tensor([[-0.0110,  0.7819, -1.1126,  0.5977, -0.5374],
        [ 1.5686, -0.7675, -1.7572, -1.2564,  0.8655],
        [-0.4227, -1.0381, -0.3254,  0.9988,  0.2015]])

In [165]:
"""
The term "logits" often refers to the raw, unnormalized scores that a model outputs before applying a softmax function 
in classification tasks.
"""
logits = model(x_data) 

In [166]:
pred_proba = nn.Softmax(dim=1)(logits)    

In [167]:
pred_proba

tensor([[1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>)

In [168]:
y_pred = pred_proba.argmax(1)
y_pred

tensor([0, 0, 0])

## Synthetic data

In [169]:
# Synthetic dataset
# Let's assume we have 100 samples
torch.manual_seed(69)

N, D_in = 100, 5
X = torch.randn(N, D_in)
y = torch.randn(N, 1)  # Synthetic labels for regression

In [170]:
X

tensor([[-5.3001e-01, -1.3035e+00,  4.4381e-01,  1.2221e+00,  1.0395e+00],
        [ 9.6085e-01,  4.2135e-01,  7.4521e-01, -1.8389e+00, -1.2497e+00],
        [-2.4846e-01,  1.4276e-01, -1.0509e+00,  3.5269e-01, -9.1552e-02],
        [ 3.4143e-02, -8.9859e-01,  1.0216e-01, -6.6273e-01, -1.3499e-01],
        [-3.9835e-01, -1.7892e+00,  1.2785e+00,  1.3351e+00, -3.0664e-01],
        [ 1.0382e+00,  1.2762e+00,  4.1880e-02, -1.2794e+00, -1.8432e+00],
        [ 8.6329e-01, -1.7786e+00, -8.0803e-01, -8.7350e-01,  9.3671e-01],
        [-1.2319e+00,  1.5287e+00, -2.7586e-01, -8.6250e-01, -1.9147e-01],
        [-4.8070e-01, -1.4154e+00,  9.3417e-02, -2.4200e-01, -1.0300e+00],
        [-2.0342e-01, -6.8820e-01, -1.7792e-02,  1.1983e+00, -8.1802e-01],
        [-7.2965e-01,  8.2558e-01,  8.7559e-01,  2.9595e-01,  6.3940e-01],
        [ 1.2406e+00, -1.2100e+00, -9.4813e-01,  6.4439e-01,  2.1877e-01],
        [-1.2224e+00, -9.3219e-01, -3.8316e-01,  1.4027e+00,  4.9127e-01],
        [ 1.0152e+00, -1.

In [171]:
y

tensor([[-2.5685e-01],
        [-4.0391e-01],
        [ 1.2753e+00],
        [-7.8397e-01],
        [ 3.7862e-01],
        [-1.1871e+00],
        [-1.4026e+00],
        [ 6.0435e-01],
        [ 1.4240e+00],
        [-1.5331e+00],
        [-1.2456e-01],
        [-4.7141e-01],
        [-5.3089e-01],
        [-1.0803e+00],
        [ 8.6601e-01],
        [-3.2139e-02],
        [-2.1301e-01],
        [ 8.6874e-01],
        [ 8.3369e-01],
        [ 3.0158e-01],
        [-5.2113e-01],
        [ 2.3907e-01],
        [ 1.4064e+00],
        [ 3.8439e-01],
        [ 2.1853e+00],
        [-7.6976e-01],
        [-4.6498e-01],
        [ 1.3144e+00],
        [ 1.1666e+00],
        [ 1.0438e+00],
        [-1.1643e+00],
        [-9.9283e-01],
        [ 8.7023e-03],
        [ 1.9184e+00],
        [ 5.1825e-02],
        [-6.6160e-01],
        [ 2.2018e+00],
        [-1.2140e+00],
        [ 3.6127e-01],
        [ 1.7435e-01],
        [-4.3098e-01],
        [ 3.8850e-01],
        [ 4.8197e-01],
        [ 8

## training ...

In [172]:
import torch.optim as optim


In [173]:
# Loss function
loss_fn = nn.MSELoss()

# Optimizer
optimizer = optim.Adam(model.parameters(), lr=1e-4)

# Training loop
epochs = 300
for epoch in range(epochs):
    # Forward pass: compute predicted y
    y_pred = model(X)

    # Compute and print loss
    loss = loss_fn(y_pred, y)
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch 0, Loss: 0.9312273263931274
Epoch 10, Loss: 0.9019464254379272
Epoch 20, Loss: 0.8760800361633301
Epoch 30, Loss: 0.8455387949943542
Epoch 40, Loss: 0.8087499737739563
Epoch 50, Loss: 0.7618715167045593
Epoch 60, Loss: 0.7072193026542664
Epoch 70, Loss: 0.6447380185127258
Epoch 80, Loss: 0.5772531032562256
Epoch 90, Loss: 0.5090678930282593
Epoch 100, Loss: 0.44148585200309753
Epoch 110, Loss: 0.37724047899246216
Epoch 120, Loss: 0.3176722228527069
Epoch 130, Loss: 0.2637220323085785
Epoch 140, Loss: 0.21478696167469025
Epoch 150, Loss: 0.17049430310726166
Epoch 160, Loss: 0.13079456984996796
Epoch 170, Loss: 0.0952078253030777
Epoch 180, Loss: 0.06583807617425919
Epoch 190, Loss: 0.04339105635881424
Epoch 200, Loss: 0.027821941301226616
Epoch 210, Loss: 0.01779797673225403
Epoch 220, Loss: 0.01168495137244463
Epoch 230, Loss: 0.00787707231938839
Epoch 240, Loss: 0.0056463866494596004
Epoch 250, Loss: 0.004114047158509493
Epoch 260, Loss: 0.0030812458135187626
Epoch 270, Loss: 0.

In [174]:
y[0]

tensor([-0.2569])

In [175]:
X.shape

torch.Size([100, 5])

In [176]:
X[0,]

tensor([-0.5300, -1.3035,  0.4438,  1.2221,  1.0395])

In [177]:
X[0,].unsqueeze(0)

tensor([[-0.5300, -1.3035,  0.4438,  1.2221,  1.0395]])

In [178]:
model.forward(X[0,].unsqueeze(0))

tensor([[-0.2616]], grad_fn=<AddmmBackward0>)

In [179]:
y[0,]

tensor([-0.2569])

In [180]:
model.forward(X)

tensor([[-2.6162e-01],
        [-4.1508e-01],
        [ 1.2143e+00],
        [-7.3719e-01],
        [ 3.7145e-01],
        [-1.1941e+00],
        [-1.4128e+00],
        [ 6.0011e-01],
        [ 1.4224e+00],
        [-1.5311e+00],
        [-1.2670e-01],
        [-4.8135e-01],
        [-5.3861e-01],
        [-1.0995e+00],
        [ 8.5911e-01],
        [-4.5739e-02],
        [-2.2134e-01],
        [ 8.6960e-01],
        [ 8.2928e-01],
        [ 2.9854e-01],
        [-5.3009e-01],
        [ 2.3297e-01],
        [ 1.3944e+00],
        [ 3.7840e-01],
        [ 2.1830e+00],
        [-7.7408e-01],
        [-4.7222e-01],
        [ 1.3063e+00],
        [ 1.1103e+00],
        [ 1.0372e+00],
        [-1.1776e+00],
        [-1.0020e+00],
        [ 1.1991e-03],
        [ 1.9126e+00],
        [ 2.4123e-01],
        [-6.7205e-01],
        [ 2.1994e+00],
        [-1.2297e+00],
        [ 3.5355e-01],
        [ 1.6887e-01],
        [-4.3367e-01],
        [ 3.9361e-01],
        [ 4.8550e-01],
        [ 8